### ISSUE TITLE
Can you add selenium-until-extra to the list?

### ISSUE THREAD

**Issue by serge1peshcoff** [christian-bromann/awesome-selenium#26]
(Disclaimer: I'm the author and the maintainer of this lib)

I wrote a library, called selenium-until-extra (https://github.com/serge1peshcoff/selenium-until-extra) that extends `selenium-webdriver`'s `until` functionality and adds some new methods to it (you can check README for more detailed description). I hope it'll be useful to somebody.

It's documented (I wrote instruction on using it and the methods description on README) and tested (there's a Travis CI set up).

Can you add it to your list?

(I can make a PR on that, if you're more comfortable with that)

**Comment by christian-bromann** [comment]
@serge1peshcoff thanks for raising the issue. I am sure your library would help a lot of people however this list doesn't cover plugins or add ons to frameworks of this list. I am afraid that it would be too cluttered if it would. I am sure that the maintainer of selenium-webdriver will add this to [their list](http://www.seleniumhq.org/download/) of add ons.
