### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by mjhea0** [christian-bromann/awesome-selenium#31]
Mind if I add a tutorials section?

I'd like to add -> [Distributed Testing with Selenium Grid and Docker
](https://testdriven.io/distributed-testing-with-selenium-grid)

**Comment by christian-bromann** [comment]
mhm .. I don't know if it is a good idea to add specific blog posts to the list. It can quickly become huge if other authors want to add their posts. I would be happy to add general resources though like Elemental Selenium.
